# Install Images
FROM bitnami/laravel:8.6.11

# Set working directory
WORKDIR /home/app

# Install packages
RUN apt-get update -y && apt-get upgrade -y

# Copy all files into working directory
COPY . .

# Expose Port
EXPOSE 8000

# Set all env
ARG DB_CONNECTION
ARG DB_HOST
ARG DB_PORT
ARG DB_DATABASE
ARG DB_USERNAME
ARG DB_PASSWORD
ARG MYSQL_SSL
ARG AZURE_STORAGE_NAME
ARG AZURE_STORAGE_KEY
ARG AZURE_STORAGE_CONTAINER
ARG AZURE_STORAGE_URL
ARG ONESIGNAL_APP_ID
ARG ONESIGNAL_REST_API_KEY
ARG ONESIGNAL_URL
ARG ONESIGNAL_ANDROID_CHANNEL_ID
ARG MAIL_MAILER
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG MAIL_ENCRYPTION
ARG MAIL_FROM_ADDRESS
ARG MAIL_FROM_NAME

ENV DB_CONNECTION $DB_CONNECTION
ENV DB_HOST $DB_HOST
ENV DB_PORT $DB_PORT
ENV DB_DATABASE $DB_DATABASE
ENV DB_USERNAME $DB_USERNAME
ENV DB_PASSWORD $DB_PASSWORD
ENV MYSQL_SSL $MYSQL_SSL
ENV AZURE_STORAGE_NAME $AZURE_STORAGE_NAME
ENV AZURE_STORAGE_KEY $AZURE_STORAGE_KEY
ENV AZURE_STORAGE_CONTAINER $AZURE_STORAGE_CONTAINER
ENV AZURE_STORAGE_URL $AZURE_STORAGE_URL
ENV ONESIGNAL_APP_ID $ONESIGNAL_APP_ID
ENV ONESIGNAL_REST_API_KEY $ONESIGNAL_REST_API_KEY
ENV ONESIGNAL_URL $ONESIGNAL_URL
ENV ONESIGNAL_ANDROID_CHANNEL_ID $ONESIGNAL_ANDROID_CHANNEL_ID
ENV MAIL_MAILER $MAIL_MAILER
ENV MAIL_HOST $MAIL_HOST
ENV MAIL_PORT $MAIL_PORT
ENV MAIL_USERNAME $MAIL_USERNAME
ENV MAIL_PASSWORD $MAIL_PASSWORD
ENV MAIL_ENCRYPTION $MAIL_ENCRYPTION
ENV MAIL_FROM_ADDRESS $MAIL_FROM_ADDRESS
ENV MAIL_FROM_NAME $MAIL_FROM_NAME

# Run Composer Update
RUN composer update && cp .env.example .env && php artisan key:generate && php artisan schedule:run

# Run script
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
